services:
  - type: web
    name: catholic-songs-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: PORT
        value: 5000
